services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uappuser", "-papppass"]
      interval: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  api-service:
    build: ./api-service
    container_name: api-service
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./api-service/.env
    ports:
      - "8000:8000"

  cache-service:
    build: ./cache-service
    container_name: cache-service
    depends_on:
      - mysql
      - redis
    environment:
      PORT: 4000
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: appdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: "06ZRIrHP4vuCIGSkGIBIcNRCpysPRxC52Cb8eKiHILvzkv2WuEjoSogZxL22sJj9"
    ports:
      - "4000:4000"

  client:
    build: ./client
    container_name: client
    depends_on:
      - api-service
      - cache-service
    ports:
      - "3000:80"

volumes:
  mysql_data:

